# Generated by Django 4.0.3 on 2022-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedRoom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numb', models.IntegerField()),
            ],
        ),
    ]
